Use 3.11 as base to build powa-web images
Otherwise image fails to build with error:

error: externally-managed-environment
× This environment is externally managed

For powa-web-git, psycopg2-binary is required sufficient.